### ISSUE TITLE
能加个访问私有Bucket文件的类方法吗？

### ISSUE THREAD

**Issue by skyfister** [johnlui/AliyunOSS#10]
能在AliyunOSS这个类里面加个访问私有Bucket里面文件并生成加密时效链接的方法吗？

**Comment by johnlui** [comment]
这个函数就是哦：https://github.com/johnlui/AliyunOSS/blob/master/OSSExample.php#L86

**Comment by skyfister** [comment]
嗷哦，好的，我检查下我的代码，调用之后生成的链接无效！
