### ISSUE TITLE
请问可以加个文件的元信息的访问方法吗

### ISSUE THREAD

**Issue by MrVokia** [johnlui/AliyunOSS#11]
你好，请问可以加个文件的元信息的访问方法吗，或者给个push权限，我提个pull request。我加了却发现没权限push @johnlui

**Comment by johnlui** [comment]
fork 之后提交更新，然后发起 pull request 就可以了

**Comment by MrVokia** [comment]
@johnlui 谢谢~

**Comment by johnlui** [comment]
@MrVokia 哈哈，不客气，感谢你的贡献！

**Comment by johnlui** [comment]
新版本已发布，可以通过 composer 安装啦
