### ISSUE TITLE
The specified bucket is not valid.

### ISSUE THREAD

**Issue by iiDestiny** [johnlui/AliyunOSS#13]
输入正确的bucket明, 我dd构造的ossClient, bucket返回null不管输入正确的还是错误的key与Secret,
AliyunOSS {#226 ▼
  #ossClient: OSSClient {#233 ▶}
  #bucket: null
}

**Comment by johnlui** [comment]
可以把你自己的解决办法发上来呦~

**Comment by iiDestiny** [comment]
在这里我给一些和我遇到问题的朋友解决一下,,,,遇到错误:The specified bucket is not valid.  的朋友   我在里我给你们解释一下 你们的内外地址肯定是给了http://***_.oss-cn-beijing.aliyuncs.com 这里的_是指bucket名字,  然后你们调用方法的时候有传入了一个bucket的名字, 然后它给你们拼接起来 就变成了http://bucketName.bucketName.oss-cn..........com     解决方案:在配置文件里面ALIOSS_SERVER=http://oss-cn-beijing.aliyuncs.com   比如这个外网地址前面不要加上 bucket名字

**Comment by johnlui** [comment]
👍

**Comment by iiDestiny** [comment]
作者你好, 那个OSS::uploadContent('文件名', '')
这里的第二个参数可以传入base64位解码后的文件流吗????? 
我用OSS::upload($tmp_file, $tmp_file);
这个函数上传也没有什么提示, oss里面也没有文件

**Comment by johnlui** [comment]
$filePath 这个变量名已经足够明显了吧。。。这是文件路径呀。。。

**Comment by iiDestiny** [comment]
不好意思....作者....太粗心了, 配置文件全是内网传输.........改成外网就可以了

**Comment by iiDestiny** [comment]
.....求博客置顶.....已经是常见问题了哈哈哈
