### ISSUE TITLE
local.ERROR: exception 'ErrorException' with message 'SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '&lt;' not found'

### ISSUE THREAD

**Issue by tonyliangli** [johnlui/AliyunOSS#17]
您好，以前使用一直正常，今天出现：local.ERROR: exception 'ErrorException' with message 'SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '&lt;' not found'，请问什么原因呢？信息！

**Comment by johnlui** [comment]
打印一下看看，应该是阿里云服务器返回了错误信息

**Comment by tonyliangli** [comment]
返回了个Resource id #464
