### ISSUE TITLE
可以获取到当前上传进度吗？一个前端的疑惑

### ISSUE THREAD

**Issue by coder0xluis** [johnlui/AliyunOSS#27]
当前我上传文件是前端ajax传递到控制器的（文件可能偏大），所以前端就有上传进度展示的需求了。

所以我的问题是：怎么去获取文件当前上传到OSS的进度呢？

**Comment by meixiaofei** [comment]
其实还是先上传到服务器 然后服务器再上传到阿里那边 所以...

**Comment by johnlui** [comment]
不能。。。
