### ISSUE TITLE
老师，您这个支持lumen 5.5.* 吗？

### ISSUE THREAD

**Issue by oknixus** [johnlui/AliyunOSS#32]

**Comment by johnlui** [comment]
全都支持，是 PHP 就支持

**Comment by oknixus** [comment]
666

**Comment by oknixus** [comment]
@johnlui 老师，为什么`composer require johnlui/aliyun-oss:~2.0`的时候，把项目中所有的依赖都更新了一遍？😓完蛋了，composer.json和composer.lock没有添加到git中！

**Comment by johnlui** [comment]
我一般把 vendor 文件夹也用 git 管理，composer.json 也用 git 管理但是只起到记录的作用，这样便于多人协作开发

**Comment by oknixus** [comment]
很好奇composer require是安装依赖的，怎么会更新不相关的依赖呢
