### ISSUE TITLE
请问上传后如何查看返回的状态？

### ISSUE THREAD

**Issue by xlkit456852** [johnlui/AliyunOSS#35]
看到demo的privateUpload方法会返回boolean的值，但是打印出来并没有？图片是能够正常上传的。

**Comment by johnlui** [comment]
目前是没有返回值的，OSS 上传我没遇到过失败，阿里云内网是很稳定的

**Comment by johnlui** [comment]
我追踪了所有的代码，发现都是有 return 的，这应该是一个保持了很多年的 bug，来自阿里云当初 beta 的 SDK，有空了我解决一下。
