### ISSUE TITLE
非常好用的一个包，支持Laravel5.2么？

### ISSUE THREAD

**Issue by OranTing** [johnlui/AliyunOSS#6]
谢谢作者的分享@johnlui

**Comment by skys215** [comment]
你在5.2使用中有什么问题吗？

**Comment by XESDog** [comment]
我在laravel5.2中按照教程中的设置，
endpoint按照阿里云官网设置
华北 2 (北京)	oss-cn-beijing	oss-cn-beijing.aliyuncs.com	oss-cn-beijing-internal.aliyuncs.com
报错如下：
Key [Endpoint] was not set

**Comment by johnlui** [comment]
完全支持
