### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by kailuo99** [johnlui/AliyunOSS#9]
我使用的是Laravel5.2 ,用了您的包以后，使用OSS出现 

ClientException in Command.php line 135:
Undefined index: host

这个如何解决？

**Comment by johnlui** [comment]
我明天会测试这个包在 5.2 下的工作情况~

**Comment by johnlui** [comment]
你这个问题是因为配置文件中 ossServer 的值未加 http://。

**Comment by kailuo99** [comment]
辛苦， 多谢~~~

**Comment by gocuntian** [comment]
"message":"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

**Comment by johnlui** [comment]
@xingcuntian 使用最新的版本了吗

**Comment by Liuran9812** [comment]
您好 我 有两个问题
1 . require:  "johnlui/aliyun-oss": "~2.0"以后，再composer update ， vendor 里并没有aliyun-oss这个文件 夹是正常吗？

2. 新建了app/services/OSS.php文件后，就报错了  说找不到文件中use JohnLui\AliyunOSS\AliyunOSS; 这个类
